// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaqriruxncwzcubjbitq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhcXJpcnV4bmN3emN1YmpiaXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjY3MjYsImV4cCI6MjA2MTM0MjcyNn0.0n3eSQUhTQ9lIWvjNDuQLvv76ohtGFiROw9qmqP5G28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);